### PR TITLE
feat: add header mobile patterns

### PR DESCRIPTION
**Pull request by thomasguillot**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-block-theme/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Similar to https://github.com/Automattic/newspack-block-theme/pull/254 but this time for the mobile header

https://github.com/user-attachments/assets/4b7edbd6-f868-45ff-86bc-f3552b11e920

### How to test the changes in this Pull Request:

See https://github.com/Automattic/newspack-block-theme/pull/254

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by thomasguillot** [comment]
I think this PR was slightly broken since it was relying on #254. Should be fixed in https://github.com/Automattic/newspack-block-theme/pull/255/commits/29496bc460637b29b42085f653511110983561b3

**Review by laurelfulford — APPROVED** [review]
Thanks @thomasguillot! The different mobile header options are nice! 

This one works as described, too. I think seeing both mobile and the desktop designs together as options is confusing, but I'm not sure of the best way to get it to work nicer. The ability to swap the template parts so easily is really nice, it's just hard to select the right spot in the header to get to the swapping, and to make sure you're picking the correct parts. 

I don't think this is a blocker to this PR at all, more of a thing to figure out down the road -- through documentation, further tweaks (maybe [additional template part areas](https://developer.wordpress.org/reference/hooks/default_wp_template_part_areas/) could help?), or something else. 🙂

**Comment by thomasguillot** [comment]
> I think seeing both mobile and the desktop designs together as options is confusing, but I'm not sure of the best way to get it to work nicer.

All I can think is we have some sort of custom interface which seems overkill.

Ideally, the pattern can support custom template-part:

```php
* Block Types: core/template-part/header-mobile
```

**Comment by laurelfulford** [comment]
For the near term at least it'll be more of an internal thing than external, since we can help folks set things up with the right pieces 🙂

**Pull request merged**
